### ISSUE TITLE
Several errors occuring

### ISSUE THREAD

**Issue by vaaarg** [jack-blackson/ioBroker.meteoalarm#128]
`PLATTFORM: LINUX
RAM: 3.7 GB
NODE.JS: V14.19.3
NPM: 6.14.17`

`host.pio4gb-Server
2022-06-04 06:30:07.264	warn	Objects 127.0.0.1:36492 Error from InMemDB: Error: Not exists

meteoalarm.2
2022-06-04 06:30:07.143	info	starting. Version 2.1.4 (non-npm: jack-blackson/ioBroker.meteoalarm) in /opt/iobroker/node_modules/iobroker.meteoalarm, node: v14.19.3, js-controller: 4.0.23
host.pio4gb
2022-06-04 06:30:06.690	info	iobroker exit 0

meteoalarm.2
2022-06-04 19:30:08.267	error	Cannot check object existence of "meteoalarm.2.alarms.Alarm_2.typeText": Connection is closed.

meteoalarm.2
2022-06-04 19:30:08.265	error	[localCreateState] error: Could not check object existence of meteoalarm.2.alarms.Alarm_2.type: Cannot check object existence of "meteoalarm.2.alarms.Alarm_2.type": Connection is closed., stack: Error: Could not check object existence of meteoalarm.2.alarms.Alarm_2.type: Cannot check object existence of "meteoalarm.2.alarms.Alarm_2.type": Connection is closed. at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:3518:30)

meteoalarm.2
2022-06-04 19:30:08.263	error	Cannot check object existence of "meteoalarm.2.alarms.Alarm_2.type": Connection is closed.

meteoalarm.2
2022-06-04 19:30:08.260	error	[localCreateState] error: Could not check object existence of meteoalarm.2.alarms.Alarm_2.levelText: Cannot check object existence of "meteoalarm.2.alarms.Alarm_2.levelText": Connection is closed., stack: Error: Could not check object existence of meteoalarm.2.alarms.Alarm_2.levelText: Cannot check object existence of "meteoalarm.2.alarms.Alarm_2.levelText": Connection is closed. at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:3518:30)

meteoalarm.2
2022-06-04 19:30:07.939	error	Cannot check object existence of "meteoalarm.2.alarms.Alarm_2.levelText": Connection is closed.

meteoalarm.2
2022-06-04 19:30:07.938	error	[localCreateState] error: DB closed, stack: Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (events.js:520:26) at Socket.emit (events.js:400:28) at Socket.emit (domain.js:475:12) at TCP.<anonymous> (net.js:686:12)`

`<html>
<body>

host.pio4gb-Server | 2022-06-04 19:30:03.008 | warn | Objects 127.0.0.1:50694 Error from InMemDB: Error: Not exists
-- | -- | -- | --
host.pio4gb-Server | 2022-06-04 19:30:02.997 | warn | Objects 127.0.0.1:50694 Error from InMemDB: Error: Not exists
host.pio4gb-Server | 2022-06-04 19:30:02.986 | warn | Objects 127.0.0.1:50694 Error from InMemDB: Error: Not exists
host.pio4gb-Server | 2022-06-04 19:30:02.976 | warn | Objects 127.0.0.1:50694 Error from InMemDB: Error: Not exists
host.pio4gb-Server | 2022-06-04 19:30:02.966 | warn | Objects 127.0.0.1:50694 Error from InMemDB: Error: Not exists
host.pio4gb-Server | 2022-06-04 19:30:02.956 | warn | Objects 127.0.0.1:50694 Error from InMemDB: Error: Not exists
host.pio4gb-Server | 2022-06-04 19:30:02.946 | warn | Objects 127.0.0.1:50694 Error from InMemDB: Error: Not exists

</body>
</html>`

**Comment by jack-blackson** [comment]
Hey! I found the problem for this error and will release a new latest version in the next days (2.1.5).

**Comment by vaaarg** [comment]
thank you @jack-blackson

**Comment by jack-blackson** [comment]
published 2.1.5 to latest
