### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ilovegym66** [jack-blackson/ioBroker.meteoalarm#150]
since some days adapter ends with this error:
`
2022-12-19 06:50:06.028  - info: meteoalarm.0 (1583309) starting. Version 2.3.1 in /opt/iobroker/node_modules/iobroker.meteoalarm, node: v16.18.1, js-controller: 4.0.24
2022-12-19 06:50:09.877  - info: meteoalarm.0 (1583309) Delete channel meteoalarm.0.alarms.249002760DWDPVW1671410220000034ddbcb-b44f-42f5-ab41-bf76698c2ad2MUL
2022-12-19 06:50:09.938  - info: meteoalarm.0 (1583309) 15.1: Updated Weather Alarms for Kreis  xxxx und Stadt xxx -> 2 alarm(s) found
2022-12-19 06:50:09.939  - info: meteoalarm.0 (1583309) Terminated (ADAPTER_REQUESTED_TERMINATION): All data processed. Adapter stopped until next scheduled process.
2022-12-19 06:50:10.459  - error: meteoalarm.0 (1583309) uncaught exception: Connection is closed.
2022-12-19 06:50:10.461  - error: meteoalarm.0 (1583309) Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:301:12)
2022-12-19 06:50:10.461  - error: meteoalarm.0 (1583309) Connection is closed.
2022-12-19 06:50:10.493  - info: host.iobrokerS instance system.adapter.meteoalarm.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

`

**Comment by jack-blackson** [comment]
Hey! I added a fix. Can you please try to install the new version 2.3.2 with this link and let me know if you still have this issue? 
https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.32

**Comment by jack-blackson** [comment]
Fix was confirmed by another user with the same issue. The fix is now moved to master and will be soon published in the latest branch.
